import "./globals.css";
import type { Metadata } from "next";
import { geistSans, geistMono } from "@/lib/fonts";
import ClickSparkGlobal from "@/animations/ClickSparkGlobal";
import SplashClient from "@/components/SplashClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClickSparkGlobal />
        <SplashClient>
          <div className="min-h-screen bg-black ">{children}</div>
        </SplashClient>
      </body>
    </html>
  );
}
